#!/usr/bin/env python3
"""Download the ten manuscript plotting CSVs from the original public release.

The CSVs are existing published numerical results, NOT outputs generated by
this reconstructed simulator. By pinning to the release commit, this script
avoids silently replacing them if the default branch later changes.
"""
from pathlib import Path
from urllib.request import urlopen
import argparse
import hashlib

# The tag v1.0-submission pointed to this commit at audit time, 9 Oct 2026.
PIN = 'b0660060a648112e095887ca2e3028af08a3df6e'
BASE = ('https://raw.githubusercontent.com/Borhan19/QThEngineering/' + PIN +
        '/FQET_GitHub_upload_starter/data/')
NAMES = [
    'bh_taskaware_family_comparison.csv',
    'bh_history_geometry.csv',
    'bh_blind_parameter_points.csv',
    'bh_blind_summary.csv',
    'crossplatform_geometry.csv',
    'ising_taskaware_phase_map.csv',
    'ising_h3_branch_curve.csv',
    'ising_solverB_spectral_audit.csv',
    'ising_h3_geometry_crossing.csv',
    'ising_h3_cost_crossing.csv',
]


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--into',default='data',help='output directory for reference CSVs')
    ap.add_argument('--overwrite',action='store_true')
    args=ap.parse_args()
    out=Path(args.into)
    out.mkdir(parents=True,exist_ok=True)
    for name in NAMES:
        target=out/name
        if target.exists() and not args.overwrite:
            print('Keeping existing',target)
            continue
        print('Fetching',name,flush=True)
        with urlopen(BASE+name,timeout=45) as response:
            blob=response.read()
        if len(blob)<20 or not blob.startswith((b'point,',b'horizon,',b's1,',b'platform,',b'g_over_J,',b'holdout_',b'branch,',b'gate,',b'horizon_Jtau,')):
            raise RuntimeError('Unexpected CSV content for '+name)
        target.write_bytes(blob)
        print(f'  {len(blob)} bytes; SHA-256 {hashlib.sha256(blob).hexdigest()}')

if __name__=='__main__':main()
